# Generated by Django 5.2.3 on 2025-06-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='birth_date',
            new_name='birthday',
        ),
    ]
