# Generated by Django 5.2.3 on 2025-06-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_birth_date_attendee_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome completo'),
        ),
    ]
