# Generated by Django 5.2.3 on 2025-06-12 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_attendee_birthday_alter_attendee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da inscrição, usado para certificados e verificações', unique=True, verbose_name='UUID'),
        ),
    ]
