# Generated by Django 5.2.3 on 2025-06-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_registration_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='present',
            field=models.BooleanField(default=False, help_text='Indica se o participante esteve presente no tutorial', verbose_name='Presente'),
        ),
    ]
