# Generated by Django 5.2.3 on 2025-07-21 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_registration_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Signatário do Certificado',
                'verbose_name_plural': 'Signatários dos Certificados',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='certificate_background',
            field=models.ImageField(blank=True, help_text='Imagem que será usada como fundo nos certificados emitidos para os tutoriais deste evento', null=True, upload_to='certificate_backgrounds/', verbose_name='Imagem de fundo do certificado'),
        ),
        migrations.AddField(
            model_name='event',
            name='certificate_title',
            field=models.CharField(blank=True, help_text='Título que será usado nos certificados emitidos para os tutoriais deste evento', max_length=255, null=True, verbose_name='Título do certificado'),
        ),
        migrations.CreateModel(
            name='EventCertificateSigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Ordem de exibição dos signatários no certificado, começando do 1', verbose_name='Ordem')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_signers', to='api.event', verbose_name='Evento')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_signers', to='api.certificatesigner', verbose_name='Signatário')),
            ],
            options={
                'verbose_name': 'Signatário do Certificado do Evento',
                'verbose_name_plural': 'Signatários dos Certificados do Evento',
                'unique_together': {('event', 'signer')},
            },
        ),
    ]
