# Generated by Django 5.2.3 on 2025-07-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_certificatesigner_event_certificate_background_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='certificate_generated',
        ),
        migrations.AddField(
            model_name='event',
            name='certificate_text',
            field=models.TextField(blank=True, help_text='Texto que será usado nos certificados emitidos para os tutoriais deste evento (use as variáveis: {attendee_name}, {tutorial_title}, {event_title}, {event_date}, {event_city}, {hours})', null=True, verbose_name='Texto do certificado'),
        ),
        migrations.AddField(
            model_name='registration',
            name='certificate_pdf',
            field=models.FileField(blank=True, help_text='PDF do certificado emitido para o participante', null=True, upload_to='certificates/', verbose_name='Certificado PDF'),
        ),
    ]
