# Generated by Django 5.2.3 on 2025-07-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_registration_certificate_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='certificate_text',
            field=models.TextField(blank=True, help_text='Texto que será usado nos certificados emitidos para os tutoriais deste evento (use as variáveis: {{ attendee_name }}, {{ tutorial_title }}, {{ event_title }}, {{ event_date }}, {{ event_city }}, {{ hours }})', null=True, verbose_name='Texto do certificado'),
        ),
    ]
