# Generated by Django 5.2.3 on 2025-07-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_event_certificate_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='certificate_background',
        ),
        migrations.RemoveField(
            model_name='event',
            name='certificate_text',
        ),
        migrations.RemoveField(
            model_name='event',
            name='certificate_title',
        ),
        migrations.AddField(
            model_name='event',
            name='certificate_template',
            field=models.FileField(blank=True, help_text='Arquivo HTML que será usado como modelo para os certificados emitidos para os tutoriais deste evento (use as variáveis: {{ attendee_name }}, {{ tutorial_title }}, {{ event_title }}, {{ event_date }}, {{ event_city }}, {{ hours }})', null=True, upload_to='certificate_templates/', verbose_name='Modelo de certificado'),
        ),
    ]
