# Generated by Django 5.2.3 on 2025-07-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_event_certificate_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatesigner',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Imagem da assinatura do signatário, usada nos certificados', null=True, upload_to='signatures/', verbose_name='Imagem da Assinatura'),
        ),
    ]
