# Generated by Django 5.2.3 on 2025-07-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_certificatesigner_signature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='certificate_sent',
            field=models.BooleanField(default=False, help_text='Indica se o certificado foi enviado por e-mail para o participante', verbose_name='Certificado enviado'),
        ),
    ]
